fMathematicaHelper <- function(mainName, params, input, import=NULL, named_arguments=NULL, vector_params=FALSE,
                               mathematica_vector=FALSE){
  switch(input$property,
         pdf=fMakeFunctionPaste(mainName=paste0("PDF[", mainName, "Distribution"),
                                params=params, postfixparams="x",
                                import=import, named_arguments=named_arguments,
                                vector_params=vector_params,
                                mathematica = T,
                                mathematica_vector=mathematica_vector),
         log_pdf=fMakeFunctionPaste(mainName=paste0("Log@PDF[", mainName, "Distribution"),
                                    params=params, postfixparams="x",
                                    import=import, named_arguments=named_arguments,
                                    vector_params=vector_params,
                                    mathematica = T,
                                    mathematica_vector=mathematica_vector),
         random=fMakeFunctionPaste(mainName=paste0("RandomVariate[", mainName, "Distribution"),
                                   params=params, postfixparams="n",
                                   import=import, named_arguments=named_arguments,
                                   vector_params=vector_params,
                                   mathematica = T,
                                   mathematica_vector=mathematica_vector))
}
fMathematicacode <- function(input){
  text <- 
    if(input$distType=='Continuous'){
      switch(input$dist,
             Normal=fMathematicaHelper("Normal",
                                       params = c(input$normal_mu, input$normal_sigma),
                                       input),
             Uniform=fMathematicaHelper("Uniform",
                                        params = c(input$uniform_a, input$uniform_b),
                                        input,
                                        vector_params = T,
                                        mathematica_vector = T),
             LogNormal=fMathematicaHelper("LogNormal",
                                          params = c(input$lognormal_mu, input$lognormal_sigma),
                                          input),
             Exponential=fMathematicaHelper("Exponential",
                                            params = input$exponential_rate, 
                                            input),
             Gamma=fMathematicaHelper("Gamma",
                                      params = c(input$gamma_shape, 1 / input$gamma_rate), 
                                      input),
             t=fMathematicaHelper("StudentT",
                                  params = c(input$t_mu,input$t_sigma, input$t_nu), 
                                  input),
             Beta=fMathematicaHelper("Beta",
                                     params = c(input$beta_a,input$beta_b), 
                                     input),
             Cauchy=fMathematicaHelper("Cauchy",
                                       params = c(input$cauchy_location,input$cauchy_scale), 
                                       input),
             HalfCauchy=fMathematicaHelper("TruncatedDistribution[{0,\\[infty]}, Cauchy",
                                           params = c(input$cauchy_location,input$cauchy_scale), 
                                           input),
             InverseGamma=fMathematicaHelper("InverseGamma",
                                             params = c(input$inversegamma_shape,input$inversegamma_scale), 
                                             input),
             InverseChiSquared=fMathematicaHelper("InverseChiSquare",
                                                  params = input$inversechisquared_df, 
                                                  input),
             LogitNormal="test"
      )
    }
  return(prismCodeBlock(text))
}
