library(shiny)

# Define UI for random distribution application 
shinyUI(fluidPage(
  
  # Application title
  titlePanel("Distribution viewer"),
  
  # Sidebar with controls to select the random distribution type
  # and number of observations to generate. Note the use of the
  # br() element to introduce extra vertical spacing
  sidebarLayout(
    sidebarPanel(
      selectInput("distType", "Category of distribution",
                   c("Continuous Univariate"="Continuous",
                     "Discrete Univariate"="Discrete",
                     "Multivariate"="Multivariate"),
                   selected="Continuous"),
      conditionalPanel("input.distType=='Continuous'",
      selectInput("dist", "Distribution type:",
                   c("Normal" = "Normal",
                     "Uniform" = "Uniform",
                     "Log-Normal" = "LogNormal",
                     "Exponential" = "Exponential",
                     "Gamma" = "Gamma",
                     "t" = "t",
                     "Beta"="Beta",
                     "Cauchy"="Cauchy",
                     "Half-Cauchy"="HalfCauchy",
                     "Inverse-Gamma"="InverseGamma",
                     "Inverse-Chi-Squared"="InverseChiSquared",
                     "Logit-Normal"="LogitNormal"))),
      conditionalPanel("input.distType=='Discrete'",
                       selectInput("dist1", "Distribution type:",
                                    c("Bernoulli" = "Bernoulli",
                                      "Binomial" = "Binomial",
                                      "Poisson" = "Poisson",
                                      "Negative-Binomial" = "NegativeBinomial",
                                      "Beta-Binomial" = "BetaBinomial"))),
      conditionalPanel("input.distType=='Multivariate'",
                       selectInput("dist2", "Distribution type:",
                                   c("Multivariate-Normal" = "MultivariateNormal",
                                     "Multivariate-t" = "MultivariateT",
                                     "Multinomial"="Multinomial",
                                     "Wishart"="Wishart",
                                     "Inverse-Wishart"="InverseWishart",
                                     "LKJ"="LKJ",
                                     "Dirichlet"="Dirichlet",
                                     "Multinomial"="Multinomial",
                                     "Categorical"="Categorical"))),
      conditionalPanel(condition="input.distType=='Continuous'&&input.dist!='Beta'",
                       sliderInput("n", "Range", value = 10,min = 0, max = 1000)),
      conditionalPanel(condition="input.distType=='Continuous'&&input.dist=='Normal'",
                       sliderInput("mu", "Mean", min=-30, max=30, value=0),
                       sliderInput("sigma", "Standard deviation", min=0.1, max=20, value=1)),
      conditionalPanel(condition="input.distType=='Continuous'&&input.dist=='Uniform'",
                       sliderInput("a", "Lower bound", min=-30, max=0, value=0),
                       sliderInput("b", "Upper bound", min=0.1, max=30, value=1)),
      conditionalPanel(condition="input.distType=='Continuous'&&input.dist=='LogNormal'",
                       sliderInput("meanlog", "Mean of log", min=-10, max=10, value=0),
                       sliderInput("sdlog", "Standard deviation of log", min=0.1, max=20, value=1)),
      conditionalPanel(condition="input.distType=='Continuous'&&input.dist=='Exponential'",
                       sliderInput("rate", "Rate parameter", min=0, max=1.1, value=0.5)),
      conditionalPanel(condition="input.distType=='Continuous'&&input.dist=='Gamma'",
                       sliderInput("shape", "Shape parameter", min=0.1, max=10, value=1),
                       sliderInput("rateGam", "Rate parameter", min=0.1, max=2, value=0.5)),
      conditionalPanel(condition="input.distType=='Continuous'&&input.dist=='t'",
                       sliderInput("muT", "mode", min=-30, max=30, value=0),
                       sliderInput("sigmaT", "sigma parameter", min=0.1, max=10, value=1),
                       sliderInput("nuT", "degrees of freedom", min=0, max=20, value=3)),
      conditionalPanel(condition="input.distType=='Continuous'&&input.dist=='Beta'",
                       sliderInput("alpha", "Shape parameter 1", min=0.5, max=10, value=1),
                       sliderInput("beta", "Shape parameter 2", min=0.5, max=10, value=1)),
      conditionalPanel(condition="input.distType=='Continuous'&&input.dist=='Cauchy'",
                       sliderInput("locationC", "location parameter", min=-30, max=30, value=0),
                       sliderInput("scaleC", "scale parameter", min=0.5, max=10, value=1)),
      conditionalPanel(condition="input.distType=='Continuous'&&input.dist=='HalfCauchy'",
                       sliderInput("locationHC", "location parameter", min=-30, max=30, value=0),
                       sliderInput("scaleHC", "scale parameter", min=0.5, max=10, value=1)),
      conditionalPanel(condition="input.distType=='Continuous'&&input.dist=='InverseGamma'",
                       sliderInput("shapeIG", "shape parameter", min=0.5, max=10, value=2),
                       sliderInput("scaleIG", "scale parameter", min=0.5, max=10, value=1)),
      conditionalPanel(condition="input.distType=='Continuous'&&input.dist=='InverseChiSquared'",
                       sliderInput("dfIC", "degrees of freedom", min=0.5, max=10, value=3)),
      conditionalPanel(condition="input.distType=='Continuous'&&input.dist=='LogitNormal'",
                       sliderInput("muLogitN", "mu parameter", min=-10, max=10, value=1),
                       sliderInput("sigmaLogitN", "sigma parameter", min=0.5, max=10, value=1)),   
      conditionalPanel(condition="input.distType=='Discrete'&&input.dist1=='Bernoulli'",
                       sliderInput("probBer", "probability", min=0, max=1, value=0.5)),
      conditionalPanel(condition="input.distType=='Discrete'&&input.dist1=='Binomial'",
                       sliderInput("sizeBin", "size", min=0, max=50, value=10),
                       sliderInput("probBin", "probability", min=0, max=1, value=0.5)),
      conditionalPanel(condition="input.distType=='Discrete'&&input.dist1=='Poisson'",
                       sliderInput("lambdaPois", "Rate", min=0, max=50, value=10, step=0.2),
                       sliderInput("rangePois", "Range", min=0, max=100, value=40)),
      conditionalPanel(condition="input.distType=='Discrete'&&input.dist1=='NegativeBinomial'",
                       sliderInput("meanNB", "Mean", min=0, max=50, value=10, step=0.2),
                       sliderInput("dispersionNB", "Dispersion", min=0, max=100, value=3,step=0.2),
                       sliderInput("rangeNB", "Range", min=0, max=100, value=40)),
      conditionalPanel(condition="input.distType=='Discrete'&&input.dist1=='BetaBinomial'",
                       sliderInput("sizeBetaBin", "Size", min=0, max=50, value=10),
                       sliderInput("shapeBetaBin1", "Shape parameter 1", min=0, max=50, value=1, step=0.2),
                       sliderInput("shapeBetaBin2", "Shape parameter 2", min=0, max=50, value=1, step=0.2)),
      conditionalPanel(condition="input.distType=='Multivariate'&&input.dist2=='MultivariateNormal'",
                       sliderInput("meanXN", "Mean of X", min=-10, max=10, value=0, step=0.2),
                       sliderInput("meanYN", "Mean of y", min=-10, max=10, value=0, step=0.2),
                       sliderInput("sigmaXN", "Standard deviation of x", min=0, max=5, value=1, step=0.2),
                       sliderInput("sigmaYN", "Standard deviation of y", min=0, max=5, value=1, step=0.2),
                       sliderInput("rhoxyN", "Correlation between x and y", min=-1, max=1, value=0, step=0.2),
                       sliderInput("rangeN", "Range of plot", min=0, max=100, value=10)),
      conditionalPanel(condition="input.distType=='Multivariate'&&input.dist2=='MultivariateT'",
                       sliderInput("meanXT", "Mode of x", min=-10, max=10, value=0, step=0.2),
                       sliderInput("meanYT", "Mode of y", min=-10, max=10, value=0, step=0.2),
                       sliderInput("sigmaXT", "Sigma x", min=0, max=5, value=1, step=0.2),
                       sliderInput("sigmaYT", "Sigma y", min=0, max=5, value=1, step=0.2),
                       sliderInput("rhoxyT", "Correlation component", min=-1, max=1, value=0,step=0.2),
                       sliderInput("dfMVT", "Degrees of freedom", min=0, max=50, value=10,step=0.2),
                       sliderInput("rangeN", "Range of plot", min=0, max=100, value=10)),
      conditionalPanel(condition="input.distType=='Multivariate'&&input.dist2=='Wishart'",
                       sliderInput("dimensionWish", "Dimensions", min=4, max=20, value=4),
                       sliderInput("dfWish", "Degrees of freedom", min=4, max=100, value=8),
                       sliderInput("sampleSizeWish", "Sample size", min=1000, max=20000, value=5000)),
      conditionalPanel(condition="input.distType=='Multivariate'&&input.dist2=='InverseWishart'",
                       sliderInput("dimensionInWish", "Dimensions", min=4, max=20, value=4),
                       sliderInput("dfInvWish", "Degrees of freedom", min=4, max=100, value=8),
                       sliderInput("sampleSizeInvWish", "Sample size", min=1000, max=20000, value=5000)),
      conditionalPanel(condition="input.distType=='Multivariate'&&input.dist2=='Dirichlet'",
                       sliderInput("dimensionsDirichlet","Dimensions",min=2,max=4,value=2,step=1),
                       sliderInput("sampleSizeDirichlet", "Sample size", min=10, max=20000, value=1000),
                       sliderInput("alphaDirichlet1","alpha 1",min=0.1,max=10,value=2),
                       sliderInput("alphaDirichlet2","alpha 2",min=0.1,max=10,value=2),
                       conditionalPanel(condition="input.dimensionsDirichlet>'2'",
                        sliderInput("alphaDirichlet3","alpha 3",min=0.1,max=10,value=2),
                        conditionalPanel(condition="input.dimensionsDirichlet>'3'",
                                         sliderInput("alphaDirichlet4","alpha 4",min=0.1,max=10,value=2)))),
      conditionalPanel(condition="input.distType=='Multivariate'&&input.dist2=='Multinomial'",
                       sliderInput("angleMultinomial","Viewpoint angle",min=0,max=360,value=100),
                       sliderInput("sizeMultinomial","size",min=2,max=100,value=6),
                       sliderInput("probMultinomial1","probability 1",min=0,max=1,value=0.5),
                       sliderInput("probMultinomial2","probability 2",min=0,max=1,value=0.5),
                       sliderInput("probMultinomial3","probability 3",min=0,max=1,value=0.5)),
      conditionalPanel(condition="input.distType=='Multivariate'&&input.dist2=='LKJ'",
                       sliderInput("dimensionLKJ", "Dimensions", min=4, max=20, value=4),
                       sliderInput("etaLKJ", "Degrees of freedom", min=0, max=40, value=1,step=0.25),
                       sliderInput("sampleSizeLKJ", "Sample size", min=1000, max=20000, value=2000)),
      br()
    ),
    # Show a tabset that includes a plot, summary, and table view
    # of the generated distribution
    mainPanel(
      uiOutput('mytabs')
    )
  )
)
)
